import { useState } from 'react';
import { ArrowRight, ArrowUpRight, Check, CircleOff, Pencil, Search, ShieldCheck, Trash2, Wrench } from 'lucide-react';
import api, { dataOf, errorText } from '../services/api.js';
import { useAuth, useLoad } from '../context/AuthContext.jsx';
import { Avatar, Button, EmptyState, ErrorState, Field, FormError, PageControls, PageLoader, Price, SectionTitle, Stars, StatusPill } from '../components/ui.jsx';

export function AdminUsers() {
  const { toast } = useAuth();
  const [search, setSearch] = useState(''), [role, setRole] = useState(''), [page, setPage] = useState(1);
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/users', { params: { ...(search ? { search } : {}), ...(role ? { role } : {}), page } })), `${search}:${role}:${page}`);
  const toggle = async user => { try { await api.patch(`/admin/users/${user._id}/active`, { isActive: !user.isActive }); await refresh(); toast(user.isActive ? 'Account disabled' : 'Account enabled'); } catch (e) { toast(errorText(e), 'error'); } };
  const items = data?.items || [];
  return <div className="admin-page"><SectionTitle eyebrow="ACCOUNT MANAGEMENT" title="People of QuickFix." copy="Manage the accounts that make up this marketplace." /><div className="admin-filter-bar"><label><Search size={16} /><input value={search} onChange={e => { setSearch(e.target.value); setPage(1); }} placeholder="Search by name or email" /></label><select value={role} onChange={e => { setRole(e.target.value); setPage(1); }} aria-label="Filter by role"><option value="">All roles</option><option value="CUSTOMER">Customers</option><option value="PROVIDER">Providers</option><option value="ADMIN">Admins</option></select></div>{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : <><div className="surface admin-table-wrap"><table className="admin-table"><thead><tr><th>Person</th><th>Role</th><th>Joined</th><th>Account</th><th>Action</th></tr></thead><tbody>{items.map(user => <tr key={user._id}><td><div className="table-person"><Avatar name={user.name} src={user.avatar} size="sm" /><span><b>{user.name}</b><small>{user.email}</small></span></div></td><td><span className="role-label">{user.role.toLowerCase()}</span></td><td>{new Date(user.createdAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</td><td><StatusPill status={user.isActive ? 'ONLINE' : 'OFFLINE'} /></td><td><button className={`table-action ${user.isActive ? 'table-disable' : 'table-enable'}`} onClick={() => toggle(user)}>{user.isActive ? <><CircleOff size={15} /> Disable</> : <><Check size={15} /> Enable</>}</button></td></tr>)}</tbody></table>{!items.length && <EmptyState title="No accounts found" copy="Try another search or change the selected role." />}</div><PageControls pagination={data?.pagination} onChange={setPage} /></>}</div>;
}

export function AdminProviders() {
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/providers')));
  return <div className="admin-page"><SectionTitle eyebrow="PROFESSIONAL NETWORK" title="The local pros." copy="A live view of provider profiles and availability." />{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : data?.length ? <div className="provider-grid provider-grid-wide">{data.map(pro => <article className="provider-card admin-provider-card" key={pro._id}><div className="provider-card-top"><Avatar name={pro.user?.name || 'QuickFix'} src={pro.user?.avatar} size="lg" /><StatusPill status={pro.status} /></div><h3>{pro.user?.name || 'Deleted account'}</h3><p>{pro.serviceArea || 'Service area not set'}</p><div className="provider-card-meta"><Stars value={pro.ratingAverage} count={pro.ratingCount} /><span>{pro.completedJobs} completed</span></div><div className="provider-categories">{pro.categories.map(c => <span key={c._id}>{c.icon} {c.name}</span>)}</div><div className="provider-card-bottom"><span>Rate <Price value={pro.hourlyRate} /><small> / hour</small></span><small className={pro.user?.isActive ? 'account-enabled' : 'account-disabled'}>{pro.user?.isActive ? 'Account active' : 'Account disabled'}</small></div></article>)}</div> : <EmptyState icon="✦" title="No providers yet" copy="New providers will appear here after they create an account." />}</div>;
}

export function AdminRequests() {
  const [status, setStatus] = useState(''), [page, setPage] = useState(1);
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/requests', { params: { ...(status ? { status } : {}), page } })), `${status}:${page}`);
  return <div className="admin-page"><SectionTitle eyebrow="MARKETPLACE HEALTH" title="Every request, in view." copy="Review service requests and follow the work in progress." /><div className="admin-filter-bar"><span>{data?.pagination?.total ?? '—'} requests</span><select value={status} onChange={e => { setStatus(e.target.value); setPage(1); }} aria-label="Filter requests by status"><option value="">Every status</option>{['OPEN', 'ACCEPTED', 'PROVIDER_ON_THE_WAY', 'STARTED', 'COMPLETED', 'CANCELLED'].map(x => <option value={x} key={x}>{x.replaceAll('_', ' ').toLowerCase()}</option>)}</select></div>{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : <><div className="surface admin-table-wrap"><table className="admin-table"><thead><tr><th>Request</th><th>Customer</th><th>Provider</th><th>Budget</th><th>Status</th></tr></thead><tbody>{(data?.items || []).map(r => <tr key={r._id}><td><a className="table-request-title" href={`/requests/${r._id}`}>{r.category?.icon} {r.title}<small>{r.city || r.address}</small></a></td><td>{r.customer?.name || '—'}</td><td>{r.provider?.name || <span className="muted">Unassigned</span>}</td><td><Price value={r.budget} /></td><td><StatusPill status={r.status} /></td></tr>)}</tbody></table>{!data?.items?.length && <EmptyState title="No requests found" copy="There are no requests with that status." />}</div><PageControls pagination={data?.pagination} onChange={setPage} /></>}</div>;
}

export function AdminCategories() {
  const { toast } = useAuth();
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/categories')));
  const [form, setForm] = useState({ name: '', slug: '', description: '', icon: '🛠️' }), [err, setErr] = useState(''), [busy, setBusy] = useState(false), [editing, setEditing] = useState('');
  const makeSlug = name => name.toLowerCase().normalize('NFD').replace(/[\u0300-\u036f]/g, '').replace(/[^a-z0-9]+/g, '-').replace(/(^-|-$)/g, '');
  const clearEditor = () => { setEditing(''); setForm({ name: '', slug: '', description: '', icon: '🛠️' }); setErr(''); };
  const create = async e => { e.preventDefault(); setErr(''); setBusy(true); try { const payload = { ...form, slug: form.slug || makeSlug(form.name) }; if (editing) await api.patch(`/admin/categories/${editing}`, payload); else await api.post('/admin/categories', payload); clearEditor(); await refresh(); toast(editing ? 'Category updated' : 'Category added'); } catch (e) { setErr(errorText(e)); } finally { setBusy(false); } };
  const archive = async category => { if (!window.confirm(`Archive ${category.name}? Existing requests will keep their category.`)) return; try { await api.delete(`/admin/categories/${category._id}`); await refresh(); toast('Category archived'); } catch (e) { setErr(errorText(e)); } };
  const edit = category => { setEditing(category._id); setErr(''); setForm({ name: category.name, slug: category.slug, description: category.description || '', icon: category.icon || '🛠️' }); window.scrollTo({ top: 0, behavior: 'smooth' }); };
  return <div className="admin-page"><SectionTitle eyebrow="SERVICE CATALOGUE" title="What QuickFix can fix." copy="Manage active service categories shown to customers and pros." /><div className="admin-category-layout"><div className="surface admin-category-form"><span className="eyebrow">{editing ? 'EDIT SERVICE CATEGORY' : 'ADD A CATEGORY'}</span><h2>{editing ? <>Give this service<br />a thoughtful update.</> : <>Make room for<br />a new kind of help.</>}</h2><form onSubmit={create}><FormError>{err}</FormError><div className="admin-category-icon-field"><Field label="Icon or emoji" value={form.icon} onChange={e => setForm({ ...form, icon: e.target.value })} maxLength="8" /><span>{form.icon || '✳'}</span></div><Field label="Category name" value={form.name} onChange={e => setForm({ ...form, name: e.target.value, slug: editing ? form.slug : makeSlug(e.target.value) })} placeholder="e.g. Gardening" maxLength="60" required /><Field label="URL slug" value={form.slug} onChange={e => setForm({ ...form, slug: e.target.value })} placeholder="gardening" required /><Field label="Short description" as="textarea" rows="3" value={form.description} onChange={e => setForm({ ...form, description: e.target.value })} maxLength="220" placeholder="What can a local pro help with?" /><Button disabled={busy}>{busy ? 'Saving…' : editing ? 'Save changes' : 'Add category'} <ArrowRight size={15} /></Button>{editing && <button type="button" className="text-button cancel-edit" onClick={clearEditor}>Cancel edit</button>}</form></div><div className="surface admin-category-list"><div className="panel-heading"><div><span className="eyebrow">THE SERVICE MENU</span><h2>All categories</h2></div><span className="results-count">{data?.length || 0}</span></div>{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : data?.length ? data.map(category => <div className={`admin-category-row ${category.isActive ? '' : 'category-archived'}`} key={category._id}><span className="admin-category-emoji">{category.icon}</span><span><b>{category.name}</b><small>{category.description}</small></span><span className={`category-state ${category.isActive ? '' : 'category-state-off'}`}>{category.isActive ? 'Active' : 'Archived'}</span>{category.isActive && <><button className="icon-button archive-button" title={`Edit ${category.name}`} onClick={() => edit(category)}><Pencil size={15} /></button><button className="icon-button archive-button" title={`Archive ${category.name}`} onClick={() => archive(category)}><Trash2 size={16} /></button></>}</div>) : <EmptyState title="No categories yet" copy="Add the first service category from the form." />}</div></div></div>;
}

export function AdminReviews() {
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/reviews')));
  return <div className="admin-page"><SectionTitle eyebrow="CUSTOMER FEEDBACK" title="The word on the work." copy="Recent customer reviews from completed jobs." />{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : data?.length ? <div className="review-list">{data.map(review => <article className="surface customer-review" key={review._id}><div className="review-card-person"><Avatar name={review.customer?.name || 'Customer'} src={review.customer?.avatar} /><span><b>{review.customer?.name}</b><small>Reviewed {new Date(review.createdAt).toLocaleDateString('en-IN', { dateStyle: 'medium' })}</small></span><Stars value={review.rating} /></div><p>{review.comment || 'No written comment.'}</p><small className="review-job">Pro: {review.provider?.name || 'Unavailable'} · {review.request?.title}</small></article>)}</div> : <EmptyState title="No reviews yet" copy="Customer reviews will show here after jobs are completed." />}</div>;
}

export function AdminActivity() {
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get('/admin/activity')));
  return <div className="admin-page"><SectionTitle eyebrow="MARKETPLACE AUDIT TRAIL" title="What’s happening." copy="A recent feed of requests, messages, reviews, and account activity." />{loading ? <PageLoader /> : error ? <ErrorState message={error} onRetry={refresh} /> : data?.length ? <div className="surface activity-feed">{data.map(row => <div className="activity-row" key={row._id}><span className="activity-marker" /><span className="activity-copy"><b>{row.title}</b><span>{row.body}</span><small>{row.user?.name || 'QuickFix'}{row.actor ? ` · by ${row.actor.name}` : ''} · {new Date(row.createdAt).toLocaleString('en-IN', { dateStyle: 'medium', timeStyle: 'short' })}</small></span>{row.request && <a href={`/requests/${row.request._id || row.request}`}>View <ArrowUpRight size={14} /></a>}</div>)}</div> : <EmptyState title="No activity yet" copy="Marketplace activity will appear here as people get things done." />}</div>;
}
