import { useEffect } from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, ArrowUpRight, BriefcaseBusiness, CalendarDays, Check, ChevronRight, CircleDollarSign, Clock3, FilePlus2, MessageCircle, Search, ShieldCheck, Sparkles, Star, TrendingUp, Wrench } from 'lucide-react';
import api, { dataOf, errorText } from '../services/api.js';
import { useAuth, useLoad } from '../context/AuthContext.jsx';
import { Avatar, Button, EmptyState, ErrorState, PageLoader, Price, RequestCard, SectionTitle, Stars } from '../components/ui.jsx';

const currency = value => `₹${Number(value || 0).toLocaleString('en-IN')}`;
export default function Dashboard() {
  const { user, socket, toast, refreshMe } = useAuth();
  const isAdmin = user.role === 'ADMIN';
  const { data, loading, error, refresh } = useLoad(async () => dataOf(await api.get(isAdmin ? '/admin/overview' : '/dashboard/summary')), `${user.role}`);
  useEffect(() => { if (!socket) return; const refreshOnChange = () => refresh(); socket.on('request:updated', refreshOnChange); socket.on('dashboard:refresh', refreshOnChange); socket.on('provider:stats:updated', refreshOnChange); return () => { socket.off('request:updated', refreshOnChange); socket.off('dashboard:refresh', refreshOnChange); socket.off('provider:stats:updated', refreshOnChange); }; }, [socket]);
  const toggleStatus = async () => { const next = data?.provider?.status === 'ONLINE' ? 'OFFLINE' : 'ONLINE'; try { await api.patch('/providers/me/status', { status: next }); await refresh(); await refreshMe(); toast(`You’re now ${next.toLowerCase()}`); } catch (e) { toast(errorText(e), 'error'); } };
  if (loading && !data) return <PageLoader label="Setting up your workspace" />;
  if (error) return <ErrorState message={error} onRetry={refresh} />;
  if (isAdmin) return <AdminDashboard data={data} />;
  const metrics = data?.metrics || {};
  const provider = user.role === 'PROVIDER';
  const items = data?.recent || [];
  return <div className="dashboard-page">
    <div className="dashboard-welcome"><div><span className="eyebrow">{provider ? 'YOUR PRO WORKSPACE' : 'YOUR HOME WORKSPACE'}</span><h1>Good {greeting()}, {user.name.split(' ')[0]}<span className="welcome-period">.</span></h1><p>{provider ? 'Here’s what’s happening with your jobs today.' : 'A little peace of mind starts with knowing what’s next.'}</p></div>{provider ? <button className={`presence-toggle ${data?.provider?.status === 'ONLINE' ? 'presence-on' : ''}`} onClick={toggleStatus}><span className="presence-light" /><span><b>{data?.provider?.status === 'ONLINE' ? 'You’re online' : data?.provider?.status === 'BUSY' ? 'You’re on a job' : 'You’re offline'}</b><small>{data?.provider?.status === 'ONLINE' ? 'Accepting nearby jobs' : 'Tap to go online'}</small></span><span className="presence-switch"><i /></span></button> : <Link to="/requests/new" className="button button-dark"><FilePlus2 size={16} /> New service request</Link>}</div>
    {!provider ? <div className="customer-hero-card"><div className="customer-hero-copy"><span className="mini-label"><Sparkles size={14} /> A BETTER KIND OF TO-DO LIST</span><h2>Something at home<br />needs a hand?</h2><p>Tell us what needs fixing and we’ll find the right person nearby.</p><Link to="/requests/new" className="button button-light">Book a service <ArrowRight size={16} /></Link></div><div className="customer-hero-art"><div className="hero-art-circle" /><div className="hero-art-key">🔑</div><div className="hero-art-note"><Check size={14} /><span><b>One less thing</b><small>on your list.</small></span></div><span className="customer-sparkle">✳</span></div></div> : <div className="provider-summary-banner"><div className="summary-profile-avatar"><Avatar name={user.name} src={user.avatar} size="xl" /></div><div><span className="eyebrow">GOOD WORK GETS NOTICED</span><h2>{data?.provider?.ratingAverage ? <><Stars value={data.provider.ratingAverage} count={data.provider.ratingCount} /> <span className="rating-caption">your pro rating</span></> : 'Make your profile shine.'}</h2><p>{data?.provider?.categories?.length ? data.provider.categories.map(c => c.name).join(' · ') : 'Add your services and show customers what you do best.'}</p></div><Link to="/profile" className="button button-outline">Edit your profile <ArrowUpRight size={16} /></Link></div>}
    <section className="metric-grid"><MetricCard icon={provider ? BriefcaseBusiness : ClipboardIcon} label={provider ? 'Jobs to review' : 'Open requests'} value={metrics.open || 0} tone="lavender" hint={provider ? 'Waiting for your response' : 'Waiting for a local pro'} /><MetricCard icon={Clock3} label={provider ? 'In progress' : 'Active services'} value={metrics.active || 0} tone="peach" hint="Moving along in real time" /><MetricCard icon={Check} label={provider ? 'Jobs completed' : 'All wrapped up'} value={metrics.completed || 0} tone="mint" hint="Good work, all done" /><MetricCard icon={MessageCircle} label="New messages" value={metrics.unreadMessages || 0} tone="blue" hint="A quick reply goes a long way" to="/inbox" /></section>
    <div className="dashboard-columns"><section className="surface recent-panel"><div className="panel-heading"><div><span className="eyebrow">LATEST ACTIVITY</span><h2>{provider ? 'Your recent jobs' : 'Your recent requests'}</h2></div><Link className="panel-link" to={provider ? '/jobs' : '/requests'}>See all <ArrowRight size={15} /></Link></div>{items.length ? <div className="request-list">{items.map(item => <RequestCard key={item._id} request={item} />)}</div> : <EmptyState icon="✳" title={provider ? 'Your next job is out there' : 'A fresh start'} copy={provider ? 'Go online to let your neighbours find a helping hand.' : 'Post a request whenever home needs a little extra care.'} action={provider ? 'Set up your pro profile' : 'Create your first request'} to={provider ? '/profile' : '/requests/new'} />}</section><aside className="side-panels"><div className="surface quick-actions"><span className="eyebrow">SHORTCUTS</span><h2>A little less<br />back-and-forth.</h2>{(provider ? [{ icon: Search, label: 'Browse incoming jobs', to: '/requests' }, { icon: MessageCircle, label: 'Open your messages', to: '/inbox' }, { icon: Star, label: 'See customer reviews', to: '/reviews' }] : [{ icon: Search, label: 'Find a trusted pro', to: '/providers' }, { icon: FilePlus2, label: 'Post a new request', to: '/requests/new' }, { icon: MessageCircle, label: 'Open your messages', to: '/inbox' }]).map(item => <Link to={item.to} key={item.to}><span className="shortcut-icon"><item.icon size={16} /></span>{item.label}<ChevronRight size={15} /></Link>)}</div><div className="support-nudge"><div className="support-nudge-icon">✦</div><div><b>Here if you need us.</b><p>Got a question? A real person can help.</p><Link to="/contact">Get in touch <ArrowRight size={14} /></Link></div></div></aside></div>
  </div>;
}
function ClipboardIcon(props) { return <CalendarDays {...props} />; }
function greeting() { const hour = new Date().getHours(); return hour < 12 ? 'morning' : hour < 18 ? 'afternoon' : 'evening'; }
function MetricCard({ icon: Icon, label, value, hint, tone, to }) { const body = <><span className={`metric-icon metric-${tone}`}><Icon size={18} /></span><span className="metric-value">{value}</span><b>{label}</b><small>{hint}</small></>; return to ? <Link to={to} className="metric-card">{body}</Link> : <div className="metric-card">{body}</div>; }

function AdminDashboard({ data }) {
  const { metrics = {}, recentRequests = [] } = data || {};
  return <div className="dashboard-page"><div className="dashboard-welcome"><div><span className="eyebrow">QUICKFIX OPERATIONS</span><h1>Good {greeting()}, Admin<span className="welcome-period">.</span></h1><p>One clear view of the marketplace today.</p></div><span className="admin-health"><i /> Marketplace running smoothly</span></div><div className="admin-metric-grid">{[['Total users', metrics.users, UsersIcon], ['Online pros', metrics.onlineProviders, Wrench], ['Open requests', metrics.openRequests, CalendarDays], ['Active jobs', metrics.activeJobs, Clock3], ['Completed jobs', metrics.completedJobs, Check], ['Reviews', metrics.reviews, Star]].map(([label, value, Icon]) => <div className="admin-metric" key={label}><span><Icon size={17} /></span><b>{value || 0}</b><small>{label}</small></div>)}</div><div className="dashboard-columns"><section className="surface recent-panel"><div className="panel-heading"><div><span className="eyebrow">MARKETPLACE ACTIVITY</span><h2>Latest requests</h2></div><Link className="panel-link" to="/admin/requests">All requests <ArrowRight size={15} /></Link></div>{recentRequests.length ? <div className="request-list">{recentRequests.map(row => <RequestCard key={row._id} request={row} />)}</div> : <EmptyState title="No activity yet" copy="New service requests will show here as customers post them." />}</section><aside className="surface admin-quick-links"><span className="eyebrow">OPERATIONS</span><h2>Keep things<br />in good shape.</h2>{[['Manage accounts', '/admin/users', UsersIcon], ['Review service providers', '/admin/providers', Wrench], ['See marketplace activity', '/admin/activity', ShieldCheck]].map(([label, to, Icon]) => <Link to={to} key={to}><Icon size={17} />{label}<ArrowRight size={14} /></Link>)}</aside></div></div>;
}
function UsersIcon(props) { return <Wrench {...props} />; }

